## Put comments here that give an overall description of what your
## functions do

## Take an inversible matrix as input and transform it into an object that cache
## the mean of this matrix and is updatable with another matrix

makeCacheMatrix <- function(x = matrix()) {
    xinv <- NULL
    
    SetMat <- function (y) {
        x <<- y
        xinv <<- NULL
    }
    
    GetMat <- function () {
        x
    }
    
    GetInv <- function () {
        xinv
    }
    
    SetInv <- function (y) {
        xinv <<- solve(y)
    }
    
    list( sm = SetMat, gm = GetMat, gi= GetInv, si = SetInv )
}


## Use an object generated by makeCacheMatrix to compute the matrix inverse or
## to get it if it is cached

cacheSolve <- function(x, ...) {
    xinv <- x$gi()
    if (is.null(xinv)) {
        message("first computation of inverse for current matrix")
        x$si(x$gm())
        xinv <- x$gi()
    }
    xinv
}
